### ISSUE TITLE
Events not showing on the map.

### ISSUE THREAD

**Issue by HamzaAnis** [usmanzaheer1995/final-year-project#1]
```
Error: Unable to find that address.
    at axios.get.then (C:\Users\hamza\Desktop\final-year-project\server\utils\myevents.js:57:31)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Why it is throwing the exception. Am I doing this wrong. What's the flow?

**Comment by usmanzaheer1995** [comment]
It searches the coordinates returned in the geocoder, if it cannot find the address, it returns this error.

**Comment by HamzaAnis** [comment]
No need for this issue to be here.
I missed the event button.
